title: User Defined Abjad Functions
description: for Google Sheets, LibreOffice Calc / AndrOpen Office Calc, MS Excel, Python and Web Pages
show_downloads: true
google_analytics:
theme: jekyll-theme-time-machine
