REM  *****  Abjad Calculation in LibreOffice Calc  *****
REM Sahur Özel'in Ebced hesaplayan abjad2numeral makrosu
REM
REM Kullanımı : Şu şekilde düzenlediğiniz hücreye girdiğiniz koordinattaki
REM             verinin belirlediğiniz ebced türünden toplamını verir.
REM
REM =abjad2numeral(Ebcedi Hesaplanacak Verinin Koordinatı; Ebced Türü)
REM
REM Hesaplanacak Ebced Türü Kodları :
REM 0 : Asğar, En küçük ebcedi arapça için verir.
REM 1 : Sağir, Küçük ebcedi arapça ve ibranice için verir.
REM 2 : Kebir, Büyük ebcedi arapça için verir.
REM 3 : Ekber, En büyük ebcedi arapça için verir.
REM 4 : Lahut, Lahut ebcedi arapça için verir.
REM 
REM Makro'nun en son güncel sürümü için aşağıdaki bağlantıya bakın.
REM https://drive.google.com/drive/folders/0B_pg_ouJHQHabktQUk9EYUtvUnM
REM 
REM Bu dosyanın son düzenleme tarihi 14 Kasım 2017 Salı 03:00
Sub abjad2numeral(stringer, Optional typology as integer) as long
AbjadSum = 0
	Select Case typology
		Case 0 
			For letterscounter = 0 to Len(stringer)
			    StringChooser = Left(stringer,Len(stringer)-letterscounter)
				ChoosenStringer = Right(StringChooser,1) 
				if ChoosenStringer = "ا" then
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "أ" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "ء" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "ى" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "إ" then 
				AbjadSum = AbjadSum + 1
				elseif ChoosenStringer = "ب" then 
				AbjadSum = AbjadSum + 2 
				elseif ChoosenStringer = "ج" then
				AbjadSum = AbjadSum + 3 
				elseif ChoosenStringer = "د" then 
				AbjadSum = AbjadSum + 4 
				elseif ChoosenStringer = "ه" then 
				AbjadSum = AbjadSum + 5 
				elseif ChoosenStringer = "و" then 
				AbjadSum = AbjadSum + 6 
				elseif ChoosenStringer = "ؤ" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "ز" then 
				AbjadSum = AbjadSum + 7 
				elseif ChoosenStringer = "ح" then 
				AbjadSum = AbjadSum + 8 
				elseif ChoosenStringer = "ط" then 
				AbjadSum = AbjadSum + 9 
				elseif ChoosenStringer = "ي" then 
				AbjadSum = AbjadSum + 10 
				elseif ChoosenStringer = "ك" then 
				AbjadSum = AbjadSum + 8 
				elseif ChoosenStringer = "ل" then 
				AbjadSum = AbjadSum + 6 
				elseif ChoosenStringer = "م" then 
				AbjadSum = AbjadSum + 4 
				elseif ChoosenStringer = "ن" then
				AbjadSum = AbjadSum + 2 
				elseif ChoosenStringer = "س" then 
				AbjadSum = AbjadSum + 0 
				elseif ChoosenStringer = "ع" then 
				AbjadSum = AbjadSum + 10 
				elseif ChoosenStringer = "ف" then 
				AbjadSum = AbjadSum + 8 
				elseif ChoosenStringer = "ص" then 
				AbjadSum = AbjadSum + 6 
				elseif ChoosenStringer = "ق" then 
				AbjadSum = AbjadSum + 4 
				elseif ChoosenStringer = "ر" then 
				AbjadSum = AbjadSum + 8 
				elseif ChoosenStringer = "ش" then 
				AbjadSum = AbjadSum + 0 
				elseif ChoosenStringer = "ت" then 
				AbjadSum = AbjadSum + 4 
				elseif ChoosenStringer = "ث" then 
				AbjadSum = AbjadSum + 8 
				elseif ChoosenStringer = "خ" then 
				AbjadSum = AbjadSum + 0 
				elseif ChoosenStringer = "ذ" then 
				AbjadSum = AbjadSum + 4 
				elseif ChoosenStringer = "ض" then 
				AbjadSum = AbjadSum + 8 
				elseif ChoosenStringer = "ظ" then 
				AbjadSum = AbjadSum + 0 
				elseif ChoosenStringer = "غ" then 
				AbjadSum = AbjadSum + 4 
				elseif ChoosenStringer = "ئ" then 
				AbjadSum = AbjadSum + 1 
				else NotLetterChar = NotLetterChar + 1  
				End if		
			Next letterscounter
		Case 1 
			For letterscounter = 0 to Len(stringer)
			    StringChooser = Left(stringer,Len(stringer)-letterscounter)
				ChoosenStringer = Right(StringChooser,1)
				if ChoosenStringer = "ا" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "ء" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "ى" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "أ" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "إ" then 
				AbjadSum = AbjadSum + 1
				elseif ChoosenStringer = "א"then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "ب" then 
				AbjadSum = AbjadSum + 2 
				elseif ChoosenStringer = "ב" then 
				AbjadSum = AbjadSum + 2
				elseif ChoosenStringer = "ج" then 
				AbjadSum = AbjadSum + 3 
				elseif ChoosenStringer = "ג" then 
				AbjadSum = AbjadSum + 3 
				elseif ChoosenStringer = "د" then 
				AbjadSum = AbjadSum + 4 
				elseif ChoosenStringer = "ד" then 
				AbjadSum = AbjadSum + 4 
				elseif ChoosenStringer = "ه" then 
				AbjadSum = AbjadSum + 5 
				elseif ChoosenStringer = "ה" then 
				AbjadSum = AbjadSum + 5
				elseif ChoosenStringer = "و" then 
				AbjadSum = AbjadSum + 6 
				elseif ChoosenStringer = "ו" then 
				AbjadSum = AbjadSum + 6 
				elseif ChoosenStringer = "ؤ" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "ز" then 
				AbjadSum = AbjadSum + 7 
				elseif ChoosenStringer = "ז" then 
				AbjadSum = AbjadSum + 7 
				elseif ChoosenStringer = "ح" then 
				AbjadSum = AbjadSum + 8 
				elseif ChoosenStringer = "ח" then 
				AbjadSum = AbjadSum + 8
				elseif ChoosenStringer = "ط" then 
				AbjadSum = AbjadSum + 9
				elseif ChoosenStringer = "ט" then 
				AbjadSum = AbjadSum + 9 
				elseif ChoosenStringer = "ي" then 
				AbjadSum = AbjadSum + 10 
				elseif ChoosenStringer = "י" then 
				AbjadSum = AbjadSum + 10
				elseif ChoosenStringer = "ك" then 
				AbjadSum = AbjadSum + 20
				elseif ChoosenStringer = "כ" then 
				AbjadSum = AbjadSum + 20 
				elseif ChoosenStringer = "ل" then 
				AbjadSum = AbjadSum + 30 
				elseif ChoosenStringer = "ל" then 
				AbjadSum = AbjadSum + 30 
				elseif ChoosenStringer = "م" then 
				AbjadSum = AbjadSum + 40 
				elseif ChoosenStringer = "מ" then 
				AbjadSum = AbjadSum + 40 
				elseif ChoosenStringer = "ن" then 
				AbjadSum = AbjadSum + 50 
				elseif ChoosenStringer = "נ" then 
				AbjadSum = AbjadSum + 50 
				elseif ChoosenStringer = "س" then 
				AbjadSum = AbjadSum + 60 
				elseif ChoosenStringer = "ס" then 
				AbjadSum = AbjadSum + 60
				elseif ChoosenStringer = "ع" then 
				AbjadSum = AbjadSum + 70 
				elseif ChoosenStringer = "ע" then 
				AbjadSum = AbjadSum + 70
				elseif ChoosenStringer = "ف" then
				AbjadSum = AbjadSum + 80 
				elseif ChoosenStringer = "פ" then
				AbjadSum = AbjadSum + 80
				elseif ChoosenStringer = "ص" then 
				AbjadSum = AbjadSum + 90 
				elseif ChoosenStringer = "צ" then 
				AbjadSum = AbjadSum + 90 
				elseif ChoosenStringer = "ق" then 
				AbjadSum = AbjadSum + 100 
				elseif ChoosenStringer = "ק" then 
				AbjadSum = AbjadSum + 100
				elseif ChoosenStringer = "ر" then 
				AbjadSum = AbjadSum + 200 
				elseif ChoosenStringer = "ר" then 
				AbjadSum = AbjadSum + 200
				elseif ChoosenStringer = "ش" then 
				AbjadSum = AbjadSum + 300 
				elseif ChoosenStringer = "ש" then 
				AbjadSum = AbjadSum + 300 
				elseif ChoosenStringer = "ت" then 
				AbjadSum = AbjadSum + 400 
				elseif ChoosenStringer = "ת" then 
				AbjadSum = AbjadSum + 400 
				elseif ChoosenStringer = "ث" then 
				AbjadSum = AbjadSum + 500 
				elseif ChoosenStringer = "ך" then 
				AbjadSum = AbjadSum + 500 
				elseif ChoosenStringer = "خ" then 
				AbjadSum = AbjadSum + 600 
				elseif ChoosenStringer = "ם" then 
				AbjadSum = AbjadSum + 600 
				elseif ChoosenStringer = "ذ" then 
				AbjadSum = AbjadSum + 700 
				elseif ChoosenStringer = "ן" then 
				AbjadSum = AbjadSum + 700 
				elseif ChoosenStringer = "ض" then 
				AbjadSum = AbjadSum + 800
				elseif ChoosenStringer = "ף" then 
				AbjadSum = AbjadSum + 800 
				elseif ChoosenStringer = "ظ" then 
				AbjadSum = AbjadSum + 900 
				elseif ChoosenStringer = "ץ" then 
				AbjadSum = AbjadSum + 900 
				elseif ChoosenStringer = "غ" then 
				AbjadSum = AbjadSum + 1000 
				elseif ChoosenStringer = "ئ" then 
				AbjadSum = AbjadSum + 1
				else NotLetterChar = NotLetterChar + 1  
				End if
			Next letterscounter
		Case 2
			For letterscounter = 0 to Len(stringer)
			    StringChooser = Left(stringer,Len(stringer)-letterscounter)
				ChoosenStringer = Right(StringChooser,1)
				if ChoosenStringer = "ا" then 
				AbjadSum = AbjadSum + 111 
				elseif ChoosenStringer = "أ" then 
				AbjadSum = AbjadSum + 111
				elseif ChoosenStringer = "ء" then 
				AbjadSum = AbjadSum + 111
				elseif ChoosenStringer = "ى" then 
				AbjadSum = AbjadSum + 111
				elseif ChoosenStringer = "إ" then 
				AbjadSum = AbjadSum + 111
				elseif ChoosenStringer = "ب" then 
				AbjadSum = AbjadSum + 3 
				elseif ChoosenStringer = "ج" then 
				AbjadSum = AbjadSum + 53 
				elseif ChoosenStringer = "د" then 
				AbjadSum = AbjadSum + 35 
				elseif ChoosenStringer = "ه" then 
				AbjadSum = AbjadSum + 6 
				elseif ChoosenStringer = "و" then 
				AbjadSum = AbjadSum + 13 
				elseif ChoosenStringer = "ؤ" then 
				AbjadSum = AbjadSum + 111
				elseif ChoosenStringer = "ز" then 
				AbjadSum = AbjadSum + 8 
				elseif ChoosenStringer = "ح" then 
				AbjadSum = AbjadSum + 9 
				elseif ChoosenStringer = "ط" then 
				AbjadSum = AbjadSum + 10 
				elseif ChoosenStringer = "ي" then 
				AbjadSum = AbjadSum + 11 
				elseif ChoosenStringer = "ك" then 
				AbjadSum = AbjadSum + 101 
				elseif ChoosenStringer = "ل" then 
				AbjadSum = AbjadSum + 71 
				elseif ChoosenStringer = "م" then 
				AbjadSum = AbjadSum + 90 
				elseif ChoosenStringer = "ن" then 
				AbjadSum = AbjadSum + 106 
				elseif ChoosenStringer = "س" then 
				AbjadSum = AbjadSum + 120 
				elseif ChoosenStringer = "ع" then 
				AbjadSum = AbjadSum + 130 
				elseif ChoosenStringer = "ف" then 
				AbjadSum = AbjadSum + 81 
				elseif ChoosenStringer = "ص" then 
				AbjadSum = AbjadSum + 95 
				elseif ChoosenStringer = "ق" then 
				AbjadSum = AbjadSum + 181 
				elseif ChoosenStringer = "ر" then 
				AbjadSum = AbjadSum + 201 
				elseif ChoosenStringer = "ش" then 
				AbjadSum = AbjadSum + 360 
				elseif ChoosenStringer = "ت" then 
				AbjadSum = AbjadSum + 401 
				elseif ChoosenStringer = "ث" then 
				AbjadSum = AbjadSum + 501 
				elseif ChoosenStringer = "خ" then 
				AbjadSum = AbjadSum + 601 
				elseif ChoosenStringer = "ذ" then 
				AbjadSum = AbjadSum + 701 
				elseif ChoosenStringer = "ض" then 
				AbjadSum = AbjadSum + 801 
				elseif ChoosenStringer = "ظ" then
				AbjadSum = AbjadSum + 901 
				elseif ChoosenStringer = "غ" then
				AbjadSum = AbjadSum + 1060 
				elseif ChoosenStringer = "ئ" then 
				AbjadSum = AbjadSum + 111
				else NotLetterChar = NotLetterChar + 1  
				End if
			Next letterscounter
		Case 3
			For letterscounter = 0 to Len(stringer)
			    StringChooser = Left(stringer,Len(stringer)-letterscounter)
				ChoosenStringer = Right(StringChooser,1)
				if ChoosenStringer = "ا" then 
				AbjadSum = AbjadSum + 19 
				elseif ChoosenStringer = "ء" then 
				AbjadSum = AbjadSum + 19
				elseif ChoosenStringer = "ى" then 
				AbjadSum = AbjadSum + 19
				elseif ChoosenStringer = "أ" then 
				AbjadSum = AbjadSum + 19
				elseif ChoosenStringer = "إ" then 
				AbjadSum = AbjadSum + 19
				elseif ChoosenStringer = "ب" then 
				AbjadSum = AbjadSum + 1002 
				elseif ChoosenStringer = "ج" then 
				AbjadSum = AbjadSum + 1331 
				elseif ChoosenStringer = "د" then 
				AbjadSum = AbjadSum + 673 
				elseif ChoosenStringer = "ه" then 
				AbjadSum = AbjadSum + 507 
				elseif ChoosenStringer = "و" then 
				AbjadSum = AbjadSum + 760 
				elseif ChoosenStringer = "ؤ" then 
				AbjadSum = AbjadSum + 760 
				elseif ChoosenStringer = "ز" then 
				AbjadSum = AbjadSum + 532 
				elseif ChoosenStringer = "ح" then 
				AbjadSum = AbjadSum + 1001 
				elseif ChoosenStringer = "ط" then 
				AbjadSum = AbjadSum + 930 
				elseif ChoosenStringer = "ي" then 
				AbjadSum = AbjadSum + 970 
				elseif ChoosenStringer = "ك" then 
				AbjadSum = AbjadSum + 696 
				elseif ChoosenStringer = "ل" then 
				AbjadSum = AbjadSum + 1087 
				elseif ChoosenStringer = "م" then 
				AbjadSum = AbjadSum + 329 
				elseif ChoosenStringer = "ن" then 
				AbjadSum = AbjadSum + 756 
				elseif ChoosenStringer = "س" then 
				AbjadSum = AbjadSum + 516 
				elseif ChoosenStringer = "ع" then 
				AbjadSum = AbjadSum + 188 
				elseif ChoosenStringer = "ف" then 
				AbjadSum = AbjadSum + 647 
				elseif ChoosenStringer = "ص" then 
				AbjadSum = AbjadSum + 586 
				elseif ChoosenStringer = "ق" then 
				AbjadSum = AbjadSum + 441 
				elseif ChoosenStringer = "ر" then 
				AbjadSum = AbjadSum + 491 
				elseif ChoosenStringer = "ش" then 
				AbjadSum = AbjadSum + 1872 
				elseif ChoosenStringer = "ت" then
				AbjadSum = AbjadSum + 1112 
				elseif ChoosenStringer = "ث" then
				AbjadSum = AbjadSum + 1471 
				elseif ChoosenStringer = "خ" then 
				AbjadSum = AbjadSum + 1301 
				elseif ChoosenStringer = "ذ" then 
				AbjadSum = AbjadSum + 973 
				elseif ChoosenStringer = "ض" then 
				AbjadSum = AbjadSum + 1442 
				elseif ChoosenStringer = "ظ" then
			    AbjadSum = AbjadSum + 1371 
				elseif ChoosenStringer = "غ" then 
				AbjadSum = AbjadSum + 111 
				elseif ChoosenStringer = "ئ" then 
				AbjadSum = AbjadSum + 19
				else NotLetterChar = NotLetterChar + 1  
				End if
			Next letterscounter
		Case 4
			For letterscounter = 0 to Len(stringer)
			    StringChooser = Left(stringer,Len(stringer)-letterscounter)
				ChoosenStringer = Right(StringChooser,1)
				if ChoosenStringer = "ا" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "ء" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "ى" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "أ" then 
				AbjadSum = AbjadSum + 1 
				elseif ChoosenStringer = "إ" then 
				AbjadSum = AbjadSum + 1
				elseif ChoosenStringer = "ب" then 
				AbjadSum = AbjadSum + 2 
				elseif ChoosenStringer = "ج" then 
				AbjadSum = AbjadSum + 3 
				elseif ChoosenStringer = "د" then 
				AbjadSum = AbjadSum + 4 
				elseif ChoosenStringer = "ه" then 
				AbjadSum = AbjadSum + 5 
				elseif ChoosenStringer = "و" then 
				AbjadSum = AbjadSum + 6 
				elseif ChoosenStringer = "ؤ" then 
				AbjadSum = AbjadSum + 1
				elseif ChoosenStringer = "ز" then 
				AbjadSum = AbjadSum + 7 
				elseif ChoosenStringer = "ح" then 
				AbjadSum = AbjadSum + 8 
				elseif ChoosenStringer = "ط" then 
				AbjadSum = AbjadSum + 9 
				elseif ChoosenStringer = "ي" then 
				AbjadSum = AbjadSum + 10 
				elseif ChoosenStringer = "ك" then 
				AbjadSum = AbjadSum + 20 
				elseif ChoosenStringer = "ل" then 
				AbjadSum = AbjadSum + 30 
				elseif ChoosenStringer = "م" then 
				AbjadSum = AbjadSum + 40 
				elseif ChoosenStringer = "ن" then 
				AbjadSum = AbjadSum + 50 
				elseif ChoosenStringer = "س" then 
				AbjadSum = AbjadSum + 60 
				elseif ChoosenStringer = "ع" then 
				AbjadSum = AbjadSum + 70 
				elseif ChoosenStringer = "ف" then 
				AbjadSum = AbjadSum + 80 
				elseif ChoosenStringer = "ص" then 
				AbjadSum = AbjadSum + 90 
				elseif ChoosenStringer = "ق" then 
				AbjadSum = AbjadSum + 100 
				elseif ChoosenStringer = "ر" then 
				AbjadSum = AbjadSum + 200 
				elseif ChoosenStringer = "ش" then 
				AbjadSum = AbjadSum + 300 
				elseif ChoosenStringer = "ت" then 
				AbjadSum = AbjadSum + 400 
				elseif ChoosenStringer = "ة" then 
				AbjadSum = AbjadSum + 400 
				elseif ChoosenStringer = "ث" then 
				AbjadSum = AbjadSum + 500 
				elseif ChoosenStringer = "خ" then 
				AbjadSum = AbjadSum + 600 
				elseif ChoosenStringer = "ذ" then 
				AbjadSum = AbjadSum + 700 
				elseif ChoosenStringer = "ض" then 
				AbjadSum = AbjadSum + 800 
				elseif ChoosenStringer = "ظ" then 
				AbjadSum = AbjadSum + 900 
				elseif ChoosenStringer = "غ" then 
				AbjadSum = AbjadSum + 1000 
				elseif ChoosenStringer = "ئ" then 
				AbjadSum = AbjadSum + 1
				else NotLetterChar = NotLetterChar + 1  
				End if
			Next letterscounter
			AbjadSum = AbjadSum + (Len(stringer)-NotLetterChar-1)
		Case Else 
			Print "Ebced Türü Belirtmemişsiniz"

	End Select
Redim AbjadSum
Redim letterscounter
Redim NotLetterChar
abjad2numeral = AbjadSum
letterscounter = 0
End Sub
